FROM ghcr.io/cirruslabs/flutter:stable

WORKDIR /app

ENV WEB_PORT=3001

CMD ["bash", "-lc", "flutter pub get && flutter run -d web-server --web-hostname 0.0.0.0 --web-port ${WEB_PORT} --disable-service-auth-codes"]
